services:
    postgres:
        image: postgres:16-alpine
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            POSTGRES_DB: ${POSTGRES_DB:-skill_tracker}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data:/var/lib/postgresql/data/pgdata
            - ./init:/docker-entrypoint-initdb.d
        ports:
            - "5500:5432"

volumes:
    postgres_data:
        name: postgres_data
